[2024-01-08T08:38:56.999+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Data_Cleaning manual__2024-01-08T08:33:51.685602+00:00 [queued]>
[2024-01-08T08:38:57.005+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: fetching_cleaning.Data_Cleaning manual__2024-01-08T08:33:51.685602+00:00 [queued]>
[2024-01-08T08:38:57.006+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:57.006+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2024-01-08T08:38:57.006+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-01-08T08:38:57.023+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): Data_Cleaning> on 2024-01-08 08:33:51.685602+00:00
[2024-01-08T08:38:57.032+0000] {standard_task_runner.py:52} INFO - Started process 279 to run task
[2024-01-08T08:38:57.035+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetching_cleaning', 'Data_Cleaning', 'manual__2024-01-08T08:33:51.685602+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpolz6nu6o', '--error-file', '/tmp/tmpfu4532op']
[2024-01-08T08:38:57.036+0000] {standard_task_runner.py:80} INFO - Job 6: Subtask Data_Cleaning
[2024-01-08T08:38:57.090+0000] {task_command.py:371} INFO - Running <TaskInstance: fetching_cleaning.Data_Cleaning manual__2024-01-08T08:33:51.685602+00:00 [running]> on host 13eafc15112b
[2024-01-08T08:38:57.130+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=saepul
AIRFLOW_CTX_DAG_ID=fetching_cleaning
AIRFLOW_CTX_TASK_ID=Data_Cleaning
AIRFLOW_CTX_EXECUTION_DATE=2024-01-08T08:33:51.685602+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-08T08:33:51.685602+00:00
[2024-01-08T08:38:57.150+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Invoice Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/steps/clean.py", line 14, in cleaning_data
    df['Invoice Date'] = pd.to_datetime(df['Invoice Date']) # merubah tipe data
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Invoice Date'
[2024-01-08T08:38:57.162+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=fetching_cleaning, task_id=Data_Cleaning, execution_date=20240108T083351, start_date=20240108T083856, end_date=20240108T083857
[2024-01-08T08:38:57.169+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 6 for task Data_Cleaning ('Invoice Date'; 279)
[2024-01-08T08:38:57.209+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-08T08:38:57.229+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
